config/routes.rb
Docus::Application.routes.draw do
  resources :users

  get "auth/login"

  get "auth/logout"

  get "auth/add_user"

  post "auth/login"

  post "auth/logout"

  post "auth/add_user"

  resources :documents

  resources :abroads

  resources :employees

  get "page/Main"

  resources :handbook_document_marks

  resources :handbook_form_admissions

  resources :handbook_abroad_traveling_reasons

  resources :handbook_jobpositions

  resources :handbook_divisions

  resources :handbook_structual_units

  resources :handbook_place_employees

  root :to => 'page#Main'

  match '/logout',  :to => 'auth#logout'
  match '/login', :to => 'auth#login'











end

app/models/handbook_abroad_traveling_reason.rb
class HandbookAbroadTravelingReason < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/handbook_abroad_traveling_reasons_controller.rb
class HandbookAbroadTravelingReasonsController < ApplicationController
  before_filter :authorize
  # GET /handbook_abroad_traveling_reasons
  # GET /handbook_abroad_traveling_reasons.json
  def index
    @handbook_abroad_traveling_reasons = HandbookAbroadTravelingReason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handbook_abroad_traveling_reasons }
    end
  end

  # GET /handbook_abroad_traveling_reasons/1
  # GET /handbook_abroad_traveling_reasons/1.json
  def show
    @handbook_abroad_traveling_reason = HandbookAbroadTravelingReason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handbook_abroad_traveling_reason }
    end
  end

  # GET /handbook_abroad_traveling_reasons/new
  # GET /handbook_abroad_traveling_reasons/new.json
  def new
    @handbook_abroad_traveling_reason = HandbookAbroadTravelingReason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @handbook_abroad_traveling_reason }
    end
  end

  # GET /handbook_abroad_traveling_reasons/1/edit
  def edit
    @handbook_abroad_traveling_reason = HandbookAbroadTravelingReason.find(params[:id])
  end

  # POST /handbook_abroad_traveling_reasons
  # POST /handbook_abroad_traveling_reasons.json
  def create
    @handbook_abroad_traveling_reason = HandbookAbroadTravelingReason.new(params[:handbook_abroad_traveling_reason])

    respond_to do |format|
      if @handbook_abroad_traveling_reason.save
        format.html { redirect_to @handbook_abroad_traveling_reason, notice: 'Handbook abroad traveling reason was successfully created.' }
        format.json { render json: @handbook_abroad_traveling_reason, status: :created, location: @handbook_abroad_traveling_reason }
      else
        format.html { render action: "new" }
        format.json { render json: @handbook_abroad_traveling_reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /handbook_abroad_traveling_reasons/1
  # PUT /handbook_abroad_traveling_reasons/1.json
  def update
    @handbook_abroad_traveling_reason = HandbookAbroadTravelingReason.find(params[:id])

    respond_to do |format|
      if @handbook_abroad_traveling_reason.update_attributes(params[:handbook_abroad_traveling_reason])
        format.html { redirect_to @handbook_abroad_traveling_reason, notice: 'Handbook abroad traveling reason was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @handbook_abroad_traveling_reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handbook_abroad_traveling_reasons/1
  # DELETE /handbook_abroad_traveling_reasons/1.json
  def destroy
    @handbook_abroad_traveling_reason = HandbookAbroadTravelingReason.find(params[:id])
    @handbook_abroad_traveling_reason.destroy

    respond_to do |format|
      format.html { redirect_to handbook_abroad_traveling_reasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/handbook_abroad_traveling_reasons_helper.rb
module HandbookAbroadTravelingReasonsHelper
end

app/views/handbook_abroad_traveling_reasons/_form.html.erb
<%= form_for(@handbook_abroad_traveling_reason) do |f| %>
  <% if @handbook_abroad_traveling_reason.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handbook_abroad_traveling_reason.errors.count, "error") %> prohibited this handbook_abroad_traveling_reason from being saved:</h2>

      <ul>
      <% @handbook_abroad_traveling_reason.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handbook_abroad_traveling_reasons/edit.html.erb
<h1>Editing handbook_abroad_traveling_reason</h1>

<%= render 'form' %>

<%= link_to 'Show', @handbook_abroad_traveling_reason %> |
<%= link_to 'Back', handbook_abroad_traveling_reasons_path %>

app/views/handbook_abroad_traveling_reasons/index.html.erb
<h1>Listing handbook_abroad_traveling_reasons</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @handbook_abroad_traveling_reasons.each do |handbook_abroad_traveling_reason| %>
  <tr>
    <td><%= handbook_abroad_traveling_reason.name %></td>
    <td><%= link_to 'Show', handbook_abroad_traveling_reason %></td>
    <td><%= link_to 'Edit', edit_handbook_abroad_traveling_reason_path(handbook_abroad_traveling_reason) %></td>
    <td><%= link_to 'Destroy', handbook_abroad_traveling_reason, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Handbook abroad traveling reason', new_handbook_abroad_traveling_reason_path %>

app/views/handbook_abroad_traveling_reasons/new.html.erb
<h1>New handbook_abroad_traveling_reason</h1>

<%= render 'form' %>

<%= link_to 'Back', handbook_abroad_traveling_reasons_path %>

app/views/handbook_abroad_traveling_reasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @handbook_abroad_traveling_reason.name %>
</p>


<%= link_to 'Edit', edit_handbook_abroad_traveling_reason_path(@handbook_abroad_traveling_reason) %> |
<%= link_to 'Back', handbook_abroad_traveling_reasons_path %>