config/routes.rb
Docus::Application.routes.draw do
  resources :users

  get "auth/login"

  get "auth/logout"

  get "auth/add_user"

  post "auth/login"

  post "auth/logout"

  post "auth/add_user"

  resources :documents

  resources :abroads

  resources :employees

  get "page/Main"

  resources :handbook_document_marks

  resources :handbook_form_admissions

  resources :handbook_abroad_traveling_reasons

  resources :handbook_jobpositions

  resources :handbook_divisions

  resources :handbook_structual_units

  resources :handbook_place_employees

  root :to => 'page#Main'

  match '/logout',  :to => 'auth#logout'
  match '/login', :to => 'auth#login'











end

app/models/handbook_division.rb
#encoding: utf-8
class HandbookDivision < ActiveRecord::Base
  attr_accessible :fullname, :shortname
  HUMANIZED_ATTRIBUTES = {
  	:fullname => "Полное наименование",
  	:shortname => "Краткое наименование"
  }
  def self.human_attribute_name(attr, options={})
	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
end

app/controllers/handbook_divisions_controller.rb
class HandbookDivisionsController < ApplicationController
  before_filter :authorize
  # GET /handbook_divisions
  # GET /handbook_divisions.json
  def index
    @handbook_divisions = HandbookDivision.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handbook_divisions }
    end
  end

  # GET /handbook_divisions/1
  # GET /handbook_divisions/1.json
  def show
    @handbook_division = HandbookDivision.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handbook_division }
    end
  end

  # GET /handbook_divisions/new
  # GET /handbook_divisions/new.json
  def new
    @handbook_division = HandbookDivision.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @handbook_division }
    end
  end

  # GET /handbook_divisions/1/edit
  def edit
    @handbook_division = HandbookDivision.find(params[:id])
  end

  # POST /handbook_divisions
  # POST /handbook_divisions.json
  def create
    @handbook_division = HandbookDivision.new(params[:handbook_division])

    respond_to do |format|
      if @handbook_division.save
        format.html { redirect_to @handbook_division, notice: 'Handbook division was successfully created.' }
        format.json { render json: @handbook_division, status: :created, location: @handbook_division }
      else
        format.html { render action: "new" }
        format.json { render json: @handbook_division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /handbook_divisions/1
  # PUT /handbook_divisions/1.json
  def update
    @handbook_division = HandbookDivision.find(params[:id])

    respond_to do |format|
      if @handbook_division.update_attributes(params[:handbook_division])
        format.html { redirect_to @handbook_division, notice: 'Handbook division was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @handbook_division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handbook_divisions/1
  # DELETE /handbook_divisions/1.json
  def destroy
    @handbook_division = HandbookDivision.find(params[:id])
    @handbook_division.destroy

    respond_to do |format|
      format.html { redirect_to handbook_divisions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/handbook_divisions_helper.rb
module HandbookDivisionsHelper
end

app/views/handbook_divisions/_form.html.erb
<%= form_for(@handbook_division) do |f| %>
  <% if @handbook_division.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handbook_division.errors.count, "error") %> prohibited this handbook_division from being saved:</h2>

      <ul>
      <% @handbook_division.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :shortname %><br />
    <%= f.text_field :shortname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handbook_divisions/edit.html.erb
<h1>Редактирование справочника "Подразделение"</h1>

<%= render 'form' %>

<%= link_to 'Показать', @handbook_division %> |
<%= link_to 'Назад', handbook_divisions_path %>

app/views/handbook_divisions/index.html.erb
<h1>Справочник "Подразделение"</h1>

<table>
  <tr>
    <th><%= HandbookDivision.human_attribute_name(:fullname) %></th>
    <th><%= HandbookDivision.human_attribute_name(:shortname) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @handbook_divisions.each do |handbook_division| %>
  <tr>
    <td><%= handbook_division.fullname %></td>
    <td><%= handbook_division.shortname %></td>
    <td><%= link_to 'Показать', handbook_division %></td>
    <td><%= link_to 'Редактировать', edit_handbook_division_path(handbook_division) %></td>
    <td><%= link_to 'Удалить', handbook_division, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить', new_handbook_division_path %>

app/views/handbook_divisions/new.html.erb
<h1>Новый элемент в справочник "Подразделение"</h1>

<%= render 'form' %>

<%= link_to 'Назад', handbook_divisions_path %>

app/views/handbook_divisions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= HandbookDivision.human_attribute_name(:fullname) %>:</b>
  <%= @handbook_division.fullname %>
</p>

<p>
  <b><%= HandbookDivision.human_attribute_name(:shortname) %>:</b>
  <%= @handbook_division.shortname %>
</p>


<%= link_to 'Редактировать', edit_handbook_division_path(@handbook_division) %> |
<%= link_to 'Назад', handbook_divisions_path %>