config/routes.rb
Docus::Application.routes.draw do
  resources :users

  get "auth/login"

  get "auth/logout"

  get "auth/add_user"

  post "auth/login"

  post "auth/logout"

  post "auth/add_user"

  resources :documents

  resources :abroads

  resources :employees

  get "page/Main"

  resources :handbook_document_marks

  resources :handbook_form_admissions

  resources :handbook_abroad_traveling_reasons

  resources :handbook_jobpositions

  resources :handbook_divisions

  resources :handbook_structual_units

  resources :handbook_place_employees

  root :to => 'page#Main'

  match '/logout',  :to => 'auth#logout'
  match '/login', :to => 'auth#login'











end

app/models/handbook_structual_unit.rb
#encoding: utf-8
class HandbookStructualUnit < ActiveRecord::Base
  attr_accessible :fullname, :shortname
  HUMANIZED_ATTRIBUTES = {
  	:fullname => "Полное наименование",
  	:shortname => "Краткое наименование"
  }
  def self.human_attribute_name(attr, options={})
	HUMANIZED_ATTRIBUTES[attr.to_sym] || super
  end
end

app/controllers/handbook_structual_units_controller.rb
class HandbookStructualUnitsController < ApplicationController
  before_filter :authorize
  # GET /handbook_structual_units
  # GET /handbook_structual_units.json
  def index
    @handbook_structual_units = HandbookStructualUnit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @handbook_structual_units }
    end
  end

  # GET /handbook_structual_units/1
  # GET /handbook_structual_units/1.json
  def show
    @handbook_structual_unit = HandbookStructualUnit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @handbook_structual_unit }
    end
  end

  # GET /handbook_structual_units/new
  # GET /handbook_structual_units/new.json
  def new
    @handbook_structual_unit = HandbookStructualUnit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @handbook_structual_unit }
    end
  end

  # GET /handbook_structual_units/1/edit
  def edit
    @handbook_structual_unit = HandbookStructualUnit.find(params[:id])
  end

  # POST /handbook_structual_units
  # POST /handbook_structual_units.json
  def create
    @handbook_structual_unit = HandbookStructualUnit.new(params[:handbook_structual_unit])

    respond_to do |format|
      if @handbook_structual_unit.save
        format.html { redirect_to @handbook_structual_unit, notice: 'Handbook structual unit was successfully created.' }
        format.json { render json: @handbook_structual_unit, status: :created, location: @handbook_structual_unit }
      else
        format.html { render action: "new" }
        format.json { render json: @handbook_structual_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /handbook_structual_units/1
  # PUT /handbook_structual_units/1.json
  def update
    @handbook_structual_unit = HandbookStructualUnit.find(params[:id])

    respond_to do |format|
      if @handbook_structual_unit.update_attributes(params[:handbook_structual_unit])
        format.html { redirect_to @handbook_structual_unit, notice: 'Handbook structual unit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @handbook_structual_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handbook_structual_units/1
  # DELETE /handbook_structual_units/1.json
  def destroy
    @handbook_structual_unit = HandbookStructualUnit.find(params[:id])
    @handbook_structual_unit.destroy

    respond_to do |format|
      format.html { redirect_to handbook_structual_units_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/handbook_structual_units_helper.rb
module HandbookStructualUnitsHelper
end

app/views/handbook_structual_units/_form.html.erb
<%= form_for(@handbook_structual_unit) do |f| %>
  <% if @handbook_structual_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@handbook_structual_unit.errors.count, "error") %> prohibited this handbook_structual_unit from being saved:</h2>

      <ul>
      <% @handbook_structual_unit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fullname %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :shortname %><br />
    <%= f.text_field :shortname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/handbook_structual_units/edit.html.erb
<h1>Редактирование справочника "Структурное подразделение"</h1>

<%= render 'form' %>

<%= link_to 'Показать', @handbook_structual_unit %> |
<%= link_to 'Назад', handbook_structual_units_path %>

app/views/handbook_structual_units/index.html.erb
<h1>Справочник "Структурное подразделение"</h1>

<table>
  <tr>
    <th><%= HandbookStructualUnit.human_attribute_name(:fullname) %></th>
    <th><%= HandbookStructualUnit.human_attribute_name(:shortname) %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @handbook_structual_units.each do |handbook_structual_unit| %>
  <tr>
    <td><%= handbook_structual_unit.fullname %></td>
    <td><%= handbook_structual_unit.shortname %></td>
    <td><%= link_to 'Показать', handbook_structual_unit %></td>
    <td><%= link_to 'Редактировать', edit_handbook_structual_unit_path(handbook_structual_unit) %></td>
    <td><%= link_to 'Удалить', handbook_structual_unit, method: :delete, data: { confirm: 'Вы уверены?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить', new_handbook_structual_unit_path %>

app/views/handbook_structual_units/new.html.erb
<h1>Новый элемент в справочник "Структурное подразделение"</h1>

<%= render 'form' %>

<%= link_to 'Назад', handbook_structual_units_path %>

app/views/handbook_structual_units/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= HandbookStructualUnit.human_attribute_name(:fullname) %>:</b>
  <%= @handbook_structual_unit.fullname %>
</p>

<p>
  <b><%= HandbookStructualUnit.human_attribute_name(:shortname) %>:</b>
  <%= @handbook_structual_unit.shortname %>
</p>


<%= link_to 'Редактировать', edit_handbook_structual_unit_path(@handbook_structual_unit) %> |
<%= link_to 'Назад', handbook_structual_units_path %>